// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ZHptQPKn8tlAHpp4s42rhSShjDitBa4',
    appId: '1:71788687452:web:49d299d0ec6284dedb3699',
    messagingSenderId: '71788687452',
    projectId: 'topreceit',
    authDomain: 'topreceit.firebaseapp.com',
    storageBucket: 'topreceit.firebasestorage.app',
    measurementId: 'G-1TR42ZCJG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC22SEY8c7rAZ97GYimGF0ycDXKVBElAkw',
    appId: '1:71788687452:android:b5ae270471e0574fdb3699',
    messagingSenderId: '71788687452',
    projectId: 'topreceit',
    storageBucket: 'topreceit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmaReOaZJ8FiC3R2kVYZdv0JMaZwt8GxE',
    appId: '1:71788687452:ios:02fc2ce3ca5ae11fdb3699',
    messagingSenderId: '71788687452',
    projectId: 'topreceit',
    storageBucket: 'topreceit.firebasestorage.app',
    iosBundleId: 'com.example.flutterTopReceit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmaReOaZJ8FiC3R2kVYZdv0JMaZwt8GxE',
    appId: '1:71788687452:ios:02fc2ce3ca5ae11fdb3699',
    messagingSenderId: '71788687452',
    projectId: 'topreceit',
    storageBucket: 'topreceit.firebasestorage.app',
    iosBundleId: 'com.example.flutterTopReceit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ZHptQPKn8tlAHpp4s42rhSShjDitBa4',
    appId: '1:71788687452:web:105f3056d3a141a5db3699',
    messagingSenderId: '71788687452',
    projectId: 'topreceit',
    authDomain: 'topreceit.firebaseapp.com',
    storageBucket: 'topreceit.firebasestorage.app',
    measurementId: 'G-RY93V17385',
  );
}
